name: Test a complete CICD process

on: pull_request

jobs:
  prefect-dbt-elt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR by removing the merge into main
        id: Checkout-code
        uses: actions/checkout@v2

      - name: Install DBT
        if: ${{ success() }}
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres
          pip install pygit2
          dbt deps

      - name: Install prefect
        run: |
          python -m pip install --upgrade pip
          pip install prefect[gitlab,dateutil,dask,distributed,great-expectations,pandas]

      - name: login prefect cloud
        run: |
          prefect backend cloud
          prefect auth login --key pcu_BALmdcZHkFBm0Hyw3s1EjbE7YFpNmJ0qYQ5N

      - name: start agent backend
        run: |
          nohup prefect agent local start -l myAgentLable > agent.log 2>&1 &

      - name: register flow
        run: |
          pwd
          ls
          prefect register --project dbt_tutorial -p ./flows/dataCompletionTest.py -n "dataCompletionTest" -l "myAgentLable"

#      - name: run prefect with dbt
#        run: |
#          prefect run -n "dataCompletionTest" --label "myAgentLable"
#
      - name: Wait for the process to finish
        run: sleep 120s
        shell: bash
